-- MySQL Script generated by MySQL Workbench
-- Sun Oct 19 21:40:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academia` DEFAULT CHARACTER SET utf8 ;
USE `academia` ;

-- -----------------------------------------------------
-- Table `academia`.`exercício`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`exercício` (
  `id_exercicio` INT(11) NOT NULL,
  `nome_exercicio` VARCHAR(255) NOT NULL,
  `series` TINYINT(4) NOT NULL,
  `repeticoes` TINYINT(4) NOT NULL,
  `carga` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id_exercicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `academia`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`treino` (
  `id_treino` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_treino` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_treino`),
  UNIQUE INDEX `nome_treino_UNIQUE` (`nome_treino` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `academia`.`exercicio_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`exercicio_treino` (
  `exercício_id` INT(11) NOT NULL,
  `treino_id` INT(11) NOT NULL,
  PRIMARY KEY (`exercício_id`, `treino_id`),
  INDEX `fk_exercícios_has_treinos_treinos1_idx` (`treino_id` ASC) VISIBLE,
  INDEX `fk_exercícios_has_treinos_exercícios1_idx` (`exercício_id` ASC) VISIBLE,
  CONSTRAINT `fk_exercícios_has_treinos_exercícios1`
    FOREIGN KEY (`exercício_id`)
    REFERENCES `academia`.`exercício` (`id_exercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercícios_has_treinos_treinos1`
    FOREIGN KEY (`treino_id`)
    REFERENCES `academia`.`treino` (`id_treino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `academia`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL DEFAULT '',
  `senha` VARCHAR(255) NOT NULL,
  `idade` DATE NOT NULL,
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `academia`.`usuario_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`usuario_treino` (
  `usuario_id_usuario` INT(11) NOT NULL,
  `treino_id_treino` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`, `treino_id_treino`),
  INDEX `fk_usuarios_has_treino_treino1_idx` (`treino_id_treino` ASC) VISIBLE,
  INDEX `fk_usuarios_has_treino_usuarios1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_treino_treino1`
    FOREIGN KEY (`treino_id_treino`)
    REFERENCES `academia`.`treino` (`id_treino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_treino_usuarios1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `academia`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
