-- MySQL Script generated by MySQL Workbench
-- seg 06 out 2025 22:15:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academia` DEFAULT CHARACTER SET utf8 ;
USE `academia` ;

-- Corrigido: sem acentos
CREATE TABLE IF NOT EXISTS `academia`.`exercicio` (
  `id_exercicio` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_exercicio` VARCHAR(255) NOT NULL,
  `series` TINYINT(4) NOT NULL,
  `repeticoes` TINYINT(4) NOT NULL,
  `carga` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id_exercicio`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `academia`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`treino` (
  `id_treino` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_treino` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_treino`),
  UNIQUE INDEX `nome_treino_UNIQUE` (`nome_treino` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `academia`.`exercicio_treino`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `academia`.`exercicio_treino` (
  `exercicio_id` INT(11) NOT NULL,
  `treino_id` INT(11) NOT NULL,
  PRIMARY KEY (`exercicio_id`, `treino_id`),
  INDEX `fk_exercicio_treino_treino_idx` (`treino_id` ASC),
  INDEX `fk_exercicio_treino_exercicio_idx` (`exercicio_id` ASC),
  CONSTRAINT `fk_exercicio_treino_exercicio`
    FOREIGN KEY (`exercicio_id`)
    REFERENCES `academia`.`exercicio` (`id_exercicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_exercicio_treino_treino`
    FOREIGN KEY (`treino_id`)
    REFERENCES `academia`.`treino` (`id_treino`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;




-- -----------------------------------------------------
-- Table `academia`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL DEFAULT '',
  `senha` VARCHAR(255) NOT NULL,
  `idade` DATE NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `academia`.`usuario_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`usuario_treino` (
  `usuario_id_usuario` INT(11) NOT NULL,
  `treino_id_treino` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`, `treino_id_treino`),
  INDEX `fk_usuarios_has_treino_treino1_idx` (`treino_id_treino` ASC) VISIBLE,
  INDEX `fk_usuarios_has_treino_usuarios1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_treino_treino1`
    FOREIGN KEY (`treino_id_treino`)
    REFERENCES `academia`.`treino` (`id_treino`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuarios_has_treino_usuarios1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `academia`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE `historico_treino` (
  `id_historico` INT AUTO_INCREMENT PRIMARY KEY,
  `usuario_id` INT NOT NULL,
  `treino_id` INT NOT NULL,
  `data_treino` DATE NOT NULL,
  `duracao_minutos` INT,
  `observacoes` VARCHAR(255),
  FOREIGN KEY (`usuario_id`) REFERENCES `usuario`(`id_usuario`),
  FOREIGN KEY (`treino_id`) REFERENCES `treino`(`id_treino`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE usuario MODIFY idade INT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
