-- MySQL Script generated by MySQL Workbench
-- seg 06 out 2025 21:30:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) COLLATE 'Default Collation' NOT NULL DEFAULT '',
  `senha` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `idade` DATE NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`treino` (
  `id_treino` INT NOT NULL AUTO_INCREMENT,
  `nome_treino` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_treino`),
  UNIQUE INDEX `nome_treino_UNIQUE` (`nome_treino` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`exercício`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exercício` (
  `id_exercicio` INT NOT NULL,
  `nome_exercicio` VARCHAR(255) NOT NULL,
  `series` TINYINT NOT NULL,
  `repeticoes` TINYINT NOT NULL,
  `carga` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id_exercicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`exercicio_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exercicio_treino` (
  `exercício_id` INT NOT NULL,
  `treino_id` INT NOT NULL,
  PRIMARY KEY (`exercício_id`, `treino_id`),
  INDEX `fk_exercícios_has_treinos_treinos1_idx` (`treino_id` ASC) VISIBLE,
  INDEX `fk_exercícios_has_treinos_exercícios1_idx` (`exercício_id` ASC) VISIBLE,
  CONSTRAINT `fk_exercícios_has_treinos_exercícios1`
    FOREIGN KEY (`exercício_id`)
    REFERENCES `mydb`.`exercício` (`id_exercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercícios_has_treinos_treinos1`
    FOREIGN KEY (`treino_id`)
    REFERENCES `mydb`.`treino` (`id_treino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_treino` (
  `usuario_id_usuario` INT NOT NULL,
  `treino_id_treino` INT NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`, `treino_id_treino`),
  INDEX `fk_usuarios_has_treino_treino1_idx` (`treino_id_treino` ASC) VISIBLE,
  INDEX `fk_usuarios_has_treino_usuarios1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_treino_usuarios1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_treino_treino1`
    FOREIGN KEY (`treino_id_treino`)
    REFERENCES `mydb`.`treino` (`id_treino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;A
